[settings]
timeout = 1000

[relaychain]
default_command = "../infrablockchain-substrate/target/release/infra-relaychain"
default_args = ["-lparachain=debug", "-l=xcm=trace"]
chain = "infra-relay-local"

[[relaychain.nodes]]
name = "alice"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7100
ws_port = 7101

[[relaychain.nodes]]
name = "bob"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7200
ws_port = 7201

[[relaychain.nodes]]
name = "charlie"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7300
ws_port = 7301

[[relaychain.nodes]]
name = "dave"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7400
ws_port = 7401

[[relaychain.nodes]]
name = "eve"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7400
ws_port = 7401

[[relaychain.nodes]]
name = "ferdie"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
rpc_port = 7400
ws_port = 7401

[[parachains]]
id = 1200
chain = "local"
cumulus_based = true

[[parachains.collators]]
name = "alice"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
command = "./target/release/infra-newnal-parachain"
rpc_port = 9500
ws_port = 9501

[[parachains.collators]]
name = "bob"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
command = "./target/release/infra-newnal-parachain"
rpc_port = 9600
ws_port = 9601

[[parachains.collators]]
name = "charlie"
validator = true
args = ["-lparachain=debug", "-l=xcm=trace"]
command = "./target/release/infra-newnal-parachain"
rpc_port = 9700
ws_port = 9701

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
